complexity:
  TooManyFunctions:
    active: false

style:
  ThrowsCount:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false

performance:
  SpreadOperator:
    active: false

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
