FROM alpine:3.16
LABEL maintainer="sig-platform@spinnaker.io"
RUN apk --no-cache add --update bash curl openjdk17-jre
RUN addgroup -S -g 10111 spinnaker
RUN adduser -S -G spinnaker -u 10111 spinnaker
COPY swabbie-web/build/install/swabbie /opt/swabbie
RUN mkdir -p /opt/swabbie/plugins && chown -R spinnaker:nogroup /opt/swabbie/plugins
USER spinnaker
HEALTHCHECK CMD curl --fail http://localhost:8092/health
CMD ["/opt/swabbie/bin/swabbie"]
