FROM ubuntu:jammy
LABEL maintainer="sig-platform@spinnaker.io"
RUN rm /var/lib/dpkg/info/libc-bin.* && apt-get clean && apt-get update && apt-get -y install curl openjdk-17-jre-headless wget
RUN adduser --system --uid 10111 --group spinnaker
COPY swabbie-web/build/install/swabbie /opt/swabbie
RUN mkdir -p /opt/swabbie/plugins && chown -R spinnaker:nogroup /opt/swabbie/plugins
USER spinnaker
HEALTHCHECK CMD curl --fail http://localhost:8092/health
CMD ["/opt/swabbie/bin/swabbie"]
