server:
  port: 7002
  ssl:
    enabled: false

redis:
  connection: redis://localhost
  port: 6379
  timeout: 30000

services:
  front50:
    baseUrl: http://localhost:8080

swagger:
  enabled: true
  title: Spinnaker Janitor API
  description:
  contact:
  patterns:
    - /resources.*

aws:
  enabled: true
  resourceTypes:
    - name: LoadBalancer
      retention: 15
      enabled: true

    - name: ServerGroup
      retention: 15
      enabled: true

    - name: SecurityGroup
      retention: 15
      enabled: true
